spring:
  datasource:
    #    url: jdbc:mysql://127.0.0.1:3306/preproject
    #    password: wkaqh12Q!
    #    url: jdbc:mysql://localhost:3306/stackoverflow
    url: jdbc:mysql://127.0.0.1:3306/stackoverflow?creatDatabaseIfNotExist=true
    password: tnthd*6682
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      #      ddl-auto: none
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
  #      open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile
logging:
  level:
    org.hibernate.sql: info
#    org.hibernate.type: trace

jwt:
  key:
    secret: ufkufisgf8wgfudsfbwe82e23eqewd11edqf123ewqd1ed1
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: admin@gmail.com
