spring:
  datasource:
    url: ${DATABASEURL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_ID}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      #      ddl-auto: none
      ddl-auto: none
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
#        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
  #      open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - email
              - profile
logging:
  level:
    org.hibernate.sql: info
  #    org.hibernate.type: trace

jwt:
  key:
    secret: ${JWT_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: ${AMDIN}
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ${MALL_ID}
    password: ${MALL_PASSWORD}
    auth: true
    starttls:
      enable: true
  subject:
    member:
      registration: 가입 환영한다 얼간이들아
  template:
    name:
      member:
        join: email-registration-member
