spring:
  datasource:
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    username: ${spring.datasource.username}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      #      ddl-auto: none
      ddl-auto: none
    properties:
      hibernate:
        highlight_sql: true
        show_sql: true
#        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
  #      open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${spring.security.oauth2.client.registration.google.client-id}
            client-secret: ${spring.security.oauth2.client.registration.google.client-secret}
            scope:
              - email
              - profile
logging:
  level:
    org.hibernate.sql: info
  #    org.hibernate.type: trace

jwt:
  key:
    secret: ${jwt.key.secret}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: admin@gmail.com
  smtp:
    host: smtp.gmail.com
    port: 587
    username: awsstudymail001@gmail.com
    password: dvsuhpduqiwzlxnb
    auth: true
    starttls:
      enable: true
  subject:
    member:
      registration: 가입 환영한다 얼간이들아
  template:
    name:
      member:
        join: email-registration-member

aws:
  paramstore:
    prefix: /preproject
    enabled: true
    profile-separator:
    name: stackoverflow