spring:
  datasource:
    #    url: jdbc:mysql://pre-project-deploy.cgk4ssfsfibv.ap-northeast-2.rds.amazonaws.com:13306/PreProject
    #    password: wkaqh12Q!
    url: jdbc:mysql://localhost:3306/stackoverflow
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
#      ddl-auto: none
          ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
#      open-in-view: false

logging:
  level:
    org.hibernate.sql: info
#    org.hibernate.type: trace