spring:
  datasource:
    url: jdbc:mysql://pre-project-deploy.cgk4ssfsfibv.ap-northeast-2.rds.amazonaws.com:13306/PreProject
    password: wkaqh12Q!
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
#      open-in-view: false

logging:
  level:
    org.hibernate.sql: info
#    org.hibernate.type: trace
#server:
#  port: 4040
