spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stackoverflow
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
      open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.hibernate.sql: info
#    org.hibernate.type: trace